name: Branch Version Bump

permissions:
  contents: write
  actions: write

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Latest Commit
        uses: actions/checkout@v4

      - name: Create Snapshot
        id: snapshot
        uses: PrismJ/maven-version-updater-action@v1.1
        with:
          type: 'snapshot'
          bump-version: false
          github-token: ${{ secrets.github_token }}
